# CEN429 - Hafta 4 demolari (Kod saglamlastirma: C/C++)
add_subdirectory(01-format-string)
add_subdirectory(02-kullanim-sonrasi)
add_subdirectory(03-tanimsiz-davranis)
add_subdirectory(04-fuzzing)
add_subdirectory(05-derleyici-korumalari)
add_subdirectory(06-sembol-dize)
add_subdirectory(07-akis-duzlestirme)
