#!/usr/bin/env python3
"""CEN429 - Week 14 - Local fallback transform (used only when Tigress is NOT installed).

Tigress (https://tigress.wtf) is a general-purpose source-to-source C obfuscator: it reads
ANY C file and applies whichever --Transform flags you name. This script does not attempt to
be that: it approximates exactly two Tigress transforms, and ONLY for this one demo's
source.c, so students without a Tigress installation still see a real, working, byte-
different-per-seed source-to-source pipeline end to end. When Tigress IS installed, demo.sh
and demo.ps1 use the real tool instead and this script is never called.

Transforms approximated (both seeded, so different --seed => different generated bytes):

  * EncodeLiterals -- VALID_TOKEN's string literal becomes a byte array, XOR-encoded with a
    seed-derived mask, decoded into a local buffer at first use. Same idea as week-09's K-07,
    done by hand there; generated here.
  * AddOpaque -- the final comparison is wrapped in a provably-ALWAYS-TRUE opaque predicate:
    for any integer q, (q*q) % 4 is never 2 (a perfect square mod 4 is always 0 or 1 -- the
    classic invariant-based opaque predicate from Collberg, Thomborson, Low, "A Taxonomy of
    Obfuscating Transformations", 1997, section 4.2). q is seed-derived, so the constant
    folded into the predicate -- and therefore the compiled bytes -- differs per seed, even
    though the predicate is always true and the branch it guards is never skipped.

Usage:
    py -3.12 fallback_transform.py <input.c> <output.c> --seed 1001
"""
import argparse
import sys

LITERAL_OLD = '    static const char VALID_TOKEN[] = "CEN429-OK";\n'
RETURN_OLD = '    return diff == 0;\n'


def transform(source_text: str, seed: int) -> str:
    if LITERAL_OLD not in source_text or RETURN_OLD not in source_text:
        sys.exit(
            "fallback_transform.py: source.c does not match the shape this fallback "
            "understands (it is written for THIS demo's source.c only, not general C -- "
            "that is exactly what makes it a fallback and not a replacement for Tigress)."
        )
    mask = (seed * 2654435761) >> 24 & 0xFF
    q = (seed * 40503) & 0x3F
    token_bytes = [ord(c) ^ mask for c in "CEN429-OK"]
    encoded_literal = (
        "    static const unsigned char VALID_TOKEN_ENC[] = {"
        + ", ".join(f"0x{b:02x}" for b in token_bytes)
        + "};\n"
        f"    const unsigned char mask = 0x{mask:02x};\n"
        "    char VALID_TOKEN[sizeof VALID_TOKEN_ENC + 1];\n"
        "    for (unsigned k = 0; k < sizeof VALID_TOKEN_ENC; k++)\n"
        "        VALID_TOKEN[k] = (char)(VALID_TOKEN_ENC[k] ^ mask);\n"
        "    VALID_TOKEN[sizeof VALID_TOKEN_ENC] = 0;\n"
    )
    opaque_return = (
        f"    unsigned q = {q}u;  /* seed-derived: changes the generated bytes, not the result */\n"
        "    if ((q * q) % 4 != 2) {  /* opaque predicate: ALWAYS true (Collberg-Thomborson-Low 1997) */\n"
        "        return diff == 0;\n"
        "    }\n"
        "    return 0xDEADu;  /* unreachable: the branch above is always taken */\n"
    )
    out = source_text.replace(LITERAL_OLD, encoded_literal, 1)
    out = out.replace(RETURN_OLD, opaque_return, 1)
    banner = (
        "/* Generated by fallback_transform.py (Tigress was not found on PATH) --\n"
        f" * approximates EncodeLiterals + AddOpaque for seed {seed}.\n"
        " * See code/week-14/01-source-to-source/README.md. Do not hand-edit; regenerate instead. */\n"
    )
    return banner + out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", help="original source file (source.c)")
    ap.add_argument("output", help="path to write the transformed source file to")
    ap.add_argument("--seed", type=int, required=True, help="diversification seed (any integer)")
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        src = f.read()
    out = transform(src, args.seed)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print(f"fallback_transform.py: wrote {args.output} (seed {args.seed})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
