# CEN429 - Hafta 6 demolari (Calisma Zamani Uygulama Oz Korumasi - RASP)
add_subdirectory(01-butunluk-hmac)
add_subdirectory(02-hata-ayiklayici)
add_subdirectory(03-ortam-zamanlama)
add_subdirectory(04-preload-kanca)
add_subdirectory(05-akis-sayaci)
add_subdirectory(06-bilesen-imza)
add_subdirectory(07-ortam-yetki)
add_subdirectory(08-tamper-yanit)
